# Generated by Django 3.1.7 on 2021-02-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=30)),
                ('date_of_release', models.DateField()),
                ('initial_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('ac', models.BooleanField(blank=True, null=True)),
                ('engine', models.CharField(max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cars.car')),
            ],
        ),
    ]
